name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs every 24 hours at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with Latest TryHackMe Badge
        run: |
          echo "![TryHackMe Badge](https://tryhackme-badges.s3.amazonaws.com/ColdCofyGuy.png)" > README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated TryHackMe badge"
          git push
